name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        include:
          - ruby: '3.3'
            coverage: '1'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Upload coverage results    
      uses: actions/upload-artifact@master
      if: ${{ matrix.coverage == '1' }}
      with:
        name: Coverage Report
        path: coverage
